export const schemes = [
  {
    id: 1,
    title: "PM Awas Yojana (Gramin & Urban)",
    desc: "Financial assistance for building houses for poor families.",
    startDate: "01/01/2025",
    endDate: "31/12/2025",
    feeDate: "No Fee (Free Scheme)",
    correctionWindow: "Not Required",
    category: "Housing",
    priority: "High",
    lastUpdated: "15/02/2025",
    status: "active"
  },
  {
    id: 2,
    title: "Ayushman Bharat PM-JAY",
    desc: "Free health insurance up to ₹5 Lakh for low-income families.",
    startDate: "Open All Year",
    endDate: "No Deadline",
    feeDate: "Free Registration",
    correctionWindow: "Not Applicable",
    category: "Health",
    priority: "High",
    lastUpdated: "20/01/2025",
    status: "active"
  },
  {
    id: 3,
    title: "National Scholarship Portal (NSP)",
    desc: "Scholarships for students from economically weaker sections.",
    startDate: "01/07/2025",
    endDate: "30/11/2025",
    feeDate: "Free (No Fee)",
    correctionWindow: "05/12/2025 - 10/12/2025",
    category: "Education",
    priority: "Medium",
    lastUpdated: "10/01/2025",
    status: "upcoming"
  },
  {
    id: 4,
    title: "Ration Card – NFSA",
    desc: "5 KG free rice/wheat per person per month under Food Security Act.",
    startDate: "01/01/2025",
    endDate: "31/12/2025",
    feeDate: "Free",
    correctionWindow: "Anytime at Ration Office",
    category: "Food Security",
    priority: "High",
    lastUpdated: "01/02/2025",
    status: "active"
  },
  {
    id: 5,
    title: "PM Kisan Samman Nidhi",
    desc: "₹6,000 per year financial support to small and marginal farmers.",
    startDate: "01/12/2024",
    endDate: "30/11/2025",
    feeDate: "Free",
    correctionWindow: "Monthly 1st-7th",
    category: "Agriculture",
    priority: "High",
    lastUpdated: "10/02/2025",
    status: "active"
  },
  {
    id: 6,
    title: "Ujjwala Yojana 2.0",
    desc: "Free LPG connections to women from BPL families.",
    startDate: "01/03/2025",
    endDate: "31/08/2025",
    feeDate: "Free",
    correctionWindow: "15 days after application",
    category: "Welfare",
    priority: "Medium",
    lastUpdated: "30/01/2025",
    status: "upcoming"
  },
  {
    id: 7,
    title: "Pradhan Mantri Matru Vandana Yojana",
    desc: "Maternity benefit program providing ₹5,000 in three installments.",
    startDate: "01/04/2024",
    endDate: "31/03/2025",
    feeDate: "Free",
    correctionWindow: "Next Quarter",
    category: "Health",
    priority: "Medium",
    lastUpdated: "05/02/2025",
    status: "active"
  },
  {
    id: 8,
    title: "Digital India Internship",
    desc: "Internship opportunities for students in digital technologies.",
    startDate: "01/06/2025",
    endDate: "31/08/2025",
    feeDate: "Free",
    correctionWindow: "First week of June",
    category: "Education",
    priority: "Low",
    lastUpdated: "25/01/2025",
    status: "upcoming"
  },
  {
    id: 9,
    title: "Pradhan Mantri Mudra Yojana",
    desc: "Loans up to ₹10 lakh to non-corporate, non-farm small enterprises.",
    startDate: "01/01/2025",
    endDate: "31/12/2025",
    feeDate: "Processing Fee Applicable",
    correctionWindow: "Within 30 days",
    category: "Finance",
    priority: "Medium",
    lastUpdated: "12/02/2025",
    status: "active"
  },
  {
    id: 10,
    title: "Atal Pension Yojana",
    desc: "Pension scheme for workers in unorganized sector.",
    startDate: "Open All Year",
    endDate: "No Deadline",
    feeDate: "Minimum Contribution",
    correctionWindow: "Anytime",
    category: "Pension",
    priority: "Medium",
    lastUpdated: "18/02/2025",
    status: "active"
  }
];